FROM openjdk:21-oracle

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn

COPY pom.xml .
RUN ./mvnw dependency:resolve

COPY src src

RUN ./mvnw clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/target/Dian-Karailiev-employees-0.0.1-SNAPSHOT.jar"]
